name: student-ai-companion
services:
  # Backend API Service
  - name: backend
    source_dir: backend
    github:
      repo: meadiljan/Student-AI-Companion
      branch: main
      deploy_on_push: true
    run_command: node dist/index.js
    build_command: npm install --production=false && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
    routes:
      - path: /api
  
  # Frontend Static Site  
  - name: frontend
    type: static_site
    source_dir: frontend
    github:
      repo: meadiljan/Student-AI-Companion
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    environment_slug: node-js
    output_dir: dist
    index_document: index.html
    error_document: index.html
    env:
      - key: VITE_API_URL
        value: https://urchin-app-qch6j.ondigitalocean.app/api
    routes:
      - path: /